name: label

on:
  pull_request:
    types:
          - opened
          - reopened
jobs:
  label:  
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pull-requests: write

    steps:

      - name: Detect Label
        id: detect
        run: |
          label=""
          case ${{ github.head_ref }} in
            added* ) label=added ;;
            changed* ) label=changed ;;
            deprecated* ) label=deprecated ;;
            removed* ) label=removed ;;
            fixed* ) label=fixed ;;
            security* ) label=security ;;
            doc* ) label=doc ;;
            * ) label=other ;;
          esac
          echo $label          
          echo "label=$label" >> "$GITHUB_OUTPUT"
      
      - name: Add Label
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['${{ steps.detect.outputs.label }}']
            })
